import pyttsx3
from firebase import firebase
from cryptography.fernet import Fernet

engine = pyttsx3.init()
rate = engine.getProperty('rate')               
engine.setProperty('rate', 150)

print("----------------------------------------------\nWelcome to Bankable Information interface !\n----------------------------------------------")

engine.say("Welcome to Bankable Information interface")
engine.say("Please enter the number associated with following facilities. 1 for Balance. 2 for Transaction")
engine.runAndWait()
key = input("\nPlease enter the number associated with following facilities:-\n1.Balance\n2.Transaction\n\nYour entry: ")

a = 2

while(a == 2):
    engine.say("Please enter your MMID number")
    engine.runAndWait()
    MMID = input("\nPlease enter your MMID: ")
    engine.say("Please verify your MMID number, {0}".format(MMID))
    engine.say("Please enter the number associated with following facilities. 1 to Proceed. 2 to re-enter the MMID number")
    engine.runAndWait()
    a = int(input("\nPlease enter the number associated with following facilities:-\n1 to Proceed.\n2 to re-enter the MMID number\n\nYour entry: "))

place = int(MMID) - int(1800221)

firebase = firebase.FirebaseApplication('https://crpyto-bank.firebaseio.com/')
address = '/crypt-data/GlArbgCoCgkYTPKN7q0L/' + str(place) + '/'
data = firebase.get(address, None)

chabi = "pBJ-07AfIo7RXhsS-32jmAfFm5hF0gz2YUm0n9Tp4a4="
f = Fernet(chabi)

if(int(key) == 1):
    balance = firebase.get(address, 'Balance')
    balance = balance.encode()
    balancedec = f.decrypt(balance)
    print("\nYour account balance : Rs.{0}\n".format(int(balancedec)))
    engine.say('Your account balance is Rupees {0}'.format(int(balancedec)))
    engine.runAndWait()
elif(int(key) == 2):
    engine.say("Please enter the number associated with following facilities. 1 for Last Credit Transaction. 2 for Last Debit Transaction")
    engine.runAndWait()
    key1 = input("\nPlease enter the number associated with following facilities:-\n1.Last Credit Transaction\n2.Last Debit Transaction\n\nYour entry: ")
    if(int(key1) == 1):
        Name = firebase.get(address, 'Credit Name')
        Name = Name.encode()
        Namedec = f.decrypt(Name)
        Namedec = Namedec.decode()
        Date = firebase.get(address, 'Credit Date')
        Date = Date.encode()
        Datedec = f.decrypt(Date)
        Datedec = Datedec.decode()
        Time = firebase.get(address, 'Credit Time')
        Time = Time.encode()
        Timedec = f.decrypt(Time)
        Timedec = Timedec.decode()
        Amount = firebase.get(address, 'Credit Amount')
        Amount = Amount.encode()
        Amountdec = f.decrypt(Amount)
        Credit_Account = firebase.get(address, 'Credit Account')
        Credit_Account = Credit_Account.encode()
        Credit_Accountdec = f.decrypt(Credit_Account)
        print("\nLast Credit Transaction details:-\n")
        print("Name:{0}".format(str(Namedec)))
        print("MMID:{0}".format(int(Credit_Accountdec)))
        print("Date:{0}".format(str(Datedec)))
        print("Time:{0}".format(str(Timedec)))
        print("Amount:Rs.{0}".format(int(Amountdec)))
        engine.say('Details of your last transaction')
        engine.say('Account Name, {0}'.format(str(Namedec)))
        engine.say('MMID Number, {0}'.format(int(Credit_Accountdec)))
        engine.say('Date, {0}'.format(str(Datedec)))
        engine.say('Time, {0}'.format(str(Timedec)))
        engine.say('Amount transfered is Rupees {0}'.format(int(Amountdec)))
        engine.runAndWait()
    elif(int(key1) == 2):
        Name = firebase.get(address, 'Debit Name')
        Name = Name.encode()
        Namedec = f.decrypt(Name)
        Namedec = Namedec.decode()
        Date = firebase.get(address, 'Debit Date')
        Date = Date.encode()
        Datedec = f.decrypt(Date)
        Datedec = Datedec.decode()
        Time = firebase.get(address, 'Debit Time')
        Time = Time.encode()
        Timedec = f.decrypt(Time)
        Timedec = Timedec.decode()
        Amount = firebase.get(address, 'Debit Amount')
        Amount = Amount.encode()
        Amountdec = f.decrypt(Amount)
        Debit_Account = firebase.get(address, 'Debit Account')
        Debit_Account = Debit_Account.encode()
        Debit_Accountdec = f.decrypt(Debit_Account)
        print("\nLast Debit Transaction details:-\n")
        print("Name:{0}".format(str(Namedec)))
        print("MMID:{0}".format(int(Debit_Accountdec)))
        print("Date:{0}".format(str(Datedec)))
        print("Time:{0}".format(str(Timedec)))
        print("Amount:Rs.{0}".format(int(Amountdec)))
        engine.say('Details of your last transaction')
        engine.say('Account Name, {0}'.format(str(Namedec)))
        engine.say('MMID Number, {0}'.format(int(Debit_Accountdec)))
        engine.say('Date, {0}'.format(str(Datedec)))
        engine.say('Time, {0}'.format(str(Timedec)))
        engine.say('Amount transfered is Rupees {0}'.format(int(Amountdec)))
        engine.runAndWait()